# Generated by Django 4.2.13 on 2024-07-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLevelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, verbose_name='User ID')),
                ('created_at', models.DateTimeField(verbose_name='Erstellt am')),
                ('created_by', models.CharField(max_length=200, verbose_name='Erstellt von')),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200, verbose_name='Gerät')),
                ('serial_number', models.CharField(max_length=200, verbose_name='Seriennummer')),
                ('device_timestamp', models.CharField(max_length=200, verbose_name='Gerätezeitstempel')),
                ('recording_type', models.CharField(max_length=200, verbose_name='Aufzeichnungstyp')),
                ('glucose_value_trend', models.CharField(max_length=200, null=True, verbose_name='Glukosewert-Verlauf mg/dL')),
                ('glucose_scan', models.CharField(max_length=200, null=True, verbose_name='Glukose-Scan mg/dL')),
                ('non_numerical_rapid_acting_insulin', models.CharField(max_length=200, null=True, verbose_name='Nicht numerisches schnellwirkendes Insulin')),
                ('rapid_acting_insulin', models.CharField(max_length=200, null=True, verbose_name='Schnellwirkendes Insulin (Einheiten)')),
                ('non_numerical_nutritional_data', models.CharField(max_length=200, null=True, verbose_name='Nicht numerische Nahrungsdaten')),
                ('carbohydrates_grams', models.CharField(max_length=200, null=True, verbose_name='Kohlenhydrate (Gramm)')),
                ('carbohydrates_portions', models.CharField(max_length=200, null=True, verbose_name='Kohlenhydrate (Portionen)')),
                ('non_numerical_depot_insulin', models.CharField(max_length=200, null=True, verbose_name='Nicht numerisches Depotinsulin')),
                ('depot_insulin', models.CharField(max_length=200, null=True, verbose_name='Depotinsulin (Einheiten)')),
                ('notes', models.CharField(max_length=200, null=True, verbose_name='Notizen')),
                ('glucose_test_strips', models.CharField(max_length=200, null=True, verbose_name='Glukose-Teststreifen mg/dL')),
                ('ketone', models.CharField(max_length=200, null=True, verbose_name='Keton mmol/L')),
                ('mealtime_insulin', models.CharField(max_length=200, null=True, verbose_name='Mahlzeiteninsulin (Einheiten)')),
                ('correction_insulin', models.CharField(max_length=200, null=True, verbose_name='Korrekturinsulin (Einheiten)')),
                ('insulin_change_by_user', models.CharField(max_length=200, null=True, verbose_name='Insulin-Änderung durch Anwender (Einheiten)')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glucose.glucoselevelmetadata')),
            ],
        ),
    ]
